version: "1.0.{build}"

configuration: Release

image:
  - Visual Studio 2015

before_build:
  # 
build_script:
  # build
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01
  - cd %APPVEYOR_BUILD_FOLDER%\build01
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION% 

build:
  verbosity: normal
  
artifacts:
  - path: build01/Release
    name: VideoCapture-v{APPVEYOR_BUILD_VERSION}

