version: "1.0.{build}"

configuration: Release

image:
  - Visual Studio 2015

before_build:
  # 
build_script:
  # build
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01\%CONFIGURATION%
  - cd %APPVEYOR_BUILD_FOLDER%\build01
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION% 

build:
  verbosity: normal
  
artifacts:
- path: build01/$(configuration)
  name: VideoCapture-v$(APPVEYOR_BUILD_VERSION)
deploy:
- provider: GitHub
  tag: VideoCapture-v$(appveyor-build-version)
  release: VideoCapture-v$(appveyor-build-version)
  description: VideoCapture-v$(appveyor-build-version)
  auth_token:
    secure: K+gxcYq4xNoMwnXQJKBieLh7U/ETaGp5dtNQiyBBetDoDuDs5n8rwgylu0DBFMY8
  repository: 5455945/VideoCapture
  artifact: ArtifactToDeploy
  draft: false
  force_update: false