version: "1.0.{build}"

configuration: Release

image:
  - Visual Studio 2015

before_build:
  # 
build_script:
  # build
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01\install
  - cd %APPVEYOR_BUILD_FOLDER%\build01
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="install" ..
  - cmake --build . --config %CONFIGURATION%
  - cmake --config %CONFIGURATION% -P cmake_install.cmake

after_build:
  - cmd: 7z a VideoCapture-{version}.zip %APPVEYOR_BUILD_FOLDER%\build01\install\bin\*

deploy:
  - provider: GitHub
  - path: VideoCapture-{version}.zip
  - name: VideoCapture-v$(appveyor-build-version)
