version: "1.0.{build}"

configuration: Release

image:
  - Visual Studio 2015

before_build:
  # 
build_script:
  # build
  - mkdir %APPVEYOR_BUILD_FOLDER%\build01
  - cd %APPVEYOR_BUILD_FOLDER%\build01
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config %CONFIGURATION% 

build:
  verbosity: normal
  
artifacts:
  - path: build01/${CONFIGURATION}
    name: VideoCapture-v{APPVEYOR_BUILD_VERSION}

deploy:
  - provider: GitHub
  - tag: TagName
  - release: ReleaseName
  - description: ReleaseDescription
  - auth_token:
  -   secure: K+gxcYq4xNoMwnXQJKBieLh7U/ETaGp5dtNQiyBBetDoDuDs5n8rwgylu0DBFMY8
  - repository: 5455945/VideoCapture
  - artifact: ArtifactsToDeploy
  - draft: false
  - force_update: false