#if(CMAKE_SIZEOF_VOID_P EQUAL 8)
#	set(_platform_suffix x64)
#else()
#	set(_platform_suffix x86)
#endif()

#set(CMAKE_VS_PLATFORM_TOOLSET "v110_xp" CACHE STRING "Platform Toolset" FORCE)

if("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 15 2017 [Ww][Ii][Nn]64)$")
  if(EXISTS $ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25415)
    set(vs2017_redist_dir "$ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25415/onecore")
  elseif(EXISTS $ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25325)
    set(vs2017_redist_dir "$ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25325")
  endif()
  #message(STATUS "vs2017_redist_dir: " ${vs2017_redist_dir})
  if(NOT ${vs2017_redist_dir})
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"${vs2017_redist_dir}/debug_nonredist/x64/Microsoft.VC141.DebugCRT/vcruntime140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/debug_nonredist/x64/Microsoft.VC141.DebugCRT/msvcp140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/debug_nonredist/x64/Microsoft.VC141.DebugCRT/vccorlib140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x64/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
  else()
    message(WARNING "vs2017 not found!")
  endif()
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 15 2017)$")
  if(EXISTS $ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25415)
    set(vs2017_redist_dir "$ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25415/onecore")
  elseif(EXISTS $ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25325)
    set(vs2017_redist_dir "$ENV{VS150COMNTOOLS}../../VC/Redist/MSVC/14.11.25325")
  endif()
  #message(STATUS "vs2017_redist_dir: " ${vs2017_redist_dir})
  if(NOT ${vs2017_redist_dir})
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"${vs2017_redist_dir}/debug_nonredist/x86/Microsoft.VC141.DebugCRT/vcruntime140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/debug_nonredist/x86/Microsoft.VC141.DebugCRT/msvcp140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/debug_nonredist/x86/Microsoft.VC141.DebugCRT/vccorlib140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"${vs2017_redist_dir}/x86/Microsoft.VC141.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
  else()
    message(WARNING "vs2017 not found!")
  endif()
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 14 2015 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC140.DebugCRT/vcruntime140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC140.DebugCRT/msvcp140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC140.DebugCRT/concrt140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC140.DebugCRT/vccorlib140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x64/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 14 2015)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC140.DebugCRT/vcruntime140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC140.DebugCRT/msvcp140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC140.DebugCRT/concrt140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC140.DebugCRT/vccorlib140d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vcruntime140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/msvcp140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/concrt140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS140COMNTOOLS}../../VC/redist/x86/Microsoft.VC140.CRT/vccorlib140.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 12 2013 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC120.DebugCRT/msvcp120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC120.DebugCRT/msvcr120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC120.DebugCRT/vccorlib120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x64/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 12 2013)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC120.DebugCRT/msvcp120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC120.DebugCRT/msvcr120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC120.DebugCRT/vccorlib120d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcp120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/msvcr120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS120COMNTOOLS}../../VC/redist/x86/Microsoft.VC120.CRT/vccorlib120.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 11 2012 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC110.DebugCRT/msvcp110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC110.DebugCRT/msvcr110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC110.DebugCRT/vccorlib110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x64/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 11 2012)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC110.DebugCRT/msvcp110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC110.DebugCRT/msvcr110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC110.DebugCRT/vccorlib110d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcp110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/msvcr110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS110COMNTOOLS}../../VC/redist/x86/Microsoft.VC110.CRT/vccorlib110.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 10 2010 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC100.DebugCRT/msvcp100d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/debug_nonredist/x64/Microsoft.VC100.DebugCRT/msvcr100d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x64/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 10 2010)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC100.DebugCRT/msvcp100d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC100.DebugCRT/msvcr100d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		#file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcp100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS100COMNTOOLS}../../VC/redist/x86/Microsoft.VC100.CRT/msvcr100.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 9 2008 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC90.DebugCRT/Microsoft.VC90.DebugCRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC90.DebugCRT/msvcm90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC90.DebugCRT/msvcp90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC90.DebugCRT/msvcr90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/amd64/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 9 2008)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC90.DebugCRT/Microsoft.VC90.DebugCRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC90.DebugCRT/msvcm90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC90.DebugCRT/msvcp90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC90.DebugCRT/msvcr90d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/Microsoft.VC90.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcm90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcp90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS90COMNTOOLS}../../VC/redist/x86/Microsoft.VC90.CRT/msvcr90.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 8 2005 [Ww][Ii][Nn]64)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC80.DebugCRT/Microsoft.VC80.DebugCRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC80.DebugCRT/msvcm80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC80.DebugCRT/msvcp80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/amd64/Microsoft.VC80.DebugCRT/msvcr80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/amd64/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
elseif("${CMAKE_GENERATOR}" MATCHES "^([Vv][Ii][Ss][Uu][Aa][Ll] [Ss][Tt][Uu][Dd][Ii][Oo] 8 2005)$")
	install(CODE "
	  if(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Dd][Ee][Bb][Uu][Gg])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC80.DebugCRT/Microsoft.VC80.DebugCRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC80.DebugCRT/msvcm80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC80.DebugCRT/msvcp80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/debug_nonredist/x86/Microsoft.VC80.DebugCRT/msvcr80d.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  elseif(\"\${CMAKE_INSTALL_CONFIG_NAME}\" MATCHES \"^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/Microsoft.VC80.CRT.manifest\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcm80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		#file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcp80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
		file(COPY \"$ENV{VS80COMNTOOLS}../../VC/redist/x86/Microsoft.VC80.CRT/msvcr80.dll\" DESTINATION \"${CMAKE_INSTALL_PREFIX}/bin/\${CMAKE_INSTALL_CONFIG_NAME}\")
	  endif()
	")
endif()
